version: '3'
services:
  leaktestservice: 
    build:
      context: .
      dockerfile: ./LeakTestService/Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=docker
    restart: on-failure
    depends_on:
      - influxdb
      - rabbitmq

  influxdb:
    image: "influxdb:latest"
    ports:
    - "8086:8086"

  rabbitmq:
    image: "rabbitmq:3-management"
    hostname: "rmq"
    ports:
      - "8080:15672"
      - "5672:5672"
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "5672" ]
      interval: 5s
      timeout: 15s
      retries: 1

